[project]
site_name = "AI in a box"
site_url = "https://dure-technologies-org.github.io/AIB-Docs/"

nav = [
  {"Home" = "index.md"},
  {"Jetson" = [
    "jetson/setup.md",
	"jetson/optimizations.md",
  "jetson/deployment.md",
	"jetson/benchmarks.md",
	"jetson/hardware.md"
  ]},
  {"Server" = [
    "server/setup.md",
  ]},
]

[project.theme]
features = [
	"navigation.tabs",
	"navigation.tabs.sticky"
]
